--- 
- 
  hosts: "10.0.1.60"
  tasks: 
    - 
      name: matplotlib
      pip: 
        name: matplotlib
- 
  hosts: "10.0.1.215"
  tasks: 
    - 
      name: bottle
      pip: 
        name: bottle
