--- 

- name: "be sure ntp is installed"
  tags: ntp
  hosts: all
  yum: 
    name: ntp
    state: installed

- name: "be sure ntp is configured"
  notify: 
    - "restart ntpd"
  tags: ntp
  template: 
    dest: /etc/ntp.conf
    src: ntp.conf.j2

- name: "be sure ntpd is running and enabled"
  service: 
    enabled: true
    name: ntpd
    state: started
  tags: ntp
