--- 
- 
  become: true
  gather_facts: false
  hosts: 10.0.1.60
  name: testServer
  pre_tasks: 
    - 
      changed_when: false
      name: "Install python for Ansible"
      raw: "test -e /usr/bin/python || (yum update && yum install -y python-minimal)"
    - 
      setup: ~
