--- 
- 
  handlers: 
    - 
      name: "restart sshd"
      service: "name=sshd state=restarted"
  hosts: all
  tasks: 
    - 
      name: "Change root password"
      user: "name=root password={{ root_password }}"
  vars: 
    - 
      root_password: HASHED_PASSWORD
    - 
      remote_password: HASHED_PASSWORD
