--- 
- 
  become: true
  hosts: all
  name: "Install notepad++"
  tasks: 
    - 
      name: "Add epel-release repo"
      yum: 
        name: epel-release
        state: present
    - 
      name: "notepad++"
      yum: 
        name: notepad++
        state: present

