---
- name: Deploy
  hosts: all
  become: yes


  tasks:
# INSTALL GIT ON REMOTE MACHINE
  - name: Install GIT
    yum:
      name:
        - git
    ignore_errors: yes

# CLONE GIT REPO ON REMOTE MACHINE
  - name: Connect to Bitbucket repo
    git:
      repo: https://bitbucket.org/nivedita0512/nec_repo_mer/src/default/
      accept_hostkey: yes
      version: master
      dest: /root/new_file
      #key_file: /home/username/.ssh/id_rsa
    

# FETCH YML FROM BITBUCKET
  - name: Fetch yml from remote
    fetch:
      remote_src: yes
      src: https://bitbucket.org/nivedita0512/nec_repo_mer/src/default/test_mer.yml
      dest: /root/new_file
      flat: yes

  - name: Run yml
    include_tasks: "https://bitbucket.org/nivedita0512/nec_repo_mer/src/default/test_mer.yml"
