--- 
- 
  become: true
  hosts: host.name.ip
  name: "Install nginx"
  tasks: 
    - 
      name: "Add epel-release repo"
      yum: 
        name: epel-release
        state: present
    - 
      name: "Install nginx"
      yum: 
        name: nginx
        state: present
    - 
      name: "Insert Index Page"
      template: 
        dest: /usr/share/nginx/html/index.html
        src: index.html
    - 
      name: "Start NGiNX"
      service: 
        name: nginx
        state: started

