--- 
- 
  become: true
  hosts: all
  name: "Install nginx"
  tasks: 
    - 
      name: "Add epel-release repo"
      yum: 
        name: epel-release
        state: present
    - 
      name: "Install nginx"
      yum: 
        name: nginx
        state: present

