--- 
- 
  become: true
  hosts: all
  name: "Install source insight"
  tasks: 
    - 
      name: "Add epel-release repo"
      yum: 
        name: epel-release
        state: present
    - 
      name: "sorce insight"
      yum: 
        name: Source Insight
        state: present

